In [1]:
import torch

In [2]:
with open('../wizard_of_oz.txt','r',encoding='utf-8') as f:
    words = f.read()

text = sorted(set(words))


In [3]:
string_to_int = { chars:i for i,chars in enumerate(text) }
int_to_string = { i:chars for i,chars in enumerate(text) }
encode = lambda s: [string_to_int[i] for i in s ]
decode = lambda l: ''.join([int_to_string[i] for i in l ])


In [4]:
data = torch.tensor(encode(words))

In [5]:
block_size = 8
batch_size = 4
n = int(0.8*len(data))
train_data = data[:n]
val_data = data[n:]


def get_batch(split):
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size,(batch_size,))
    x = torch.stack([data[i:i+block_size]for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])

    return x,y

get_batch('train')

(tensor([[56,  6,  1, 50, 65, 65, 54, 50],
         [57, 50, 69,  1, 68, 54, 54, 62],
         [70, 67, 54,  1, 72, 58, 69, 57],
         [58, 63, 69, 54, 63, 53,  1, 69]]),
 tensor([[ 6,  1, 50, 65, 65, 54, 50, 61],
         [50, 69,  1, 68, 54, 54, 62, 54],
         [67, 54,  1, 72, 58, 69, 57, 64],
         [63, 69, 54, 63, 53,  1, 69, 64]]))

In [6]:
torch.randint(5,(7,))

tensor([2, 0, 2, 2, 4, 4, 2])