In [3]:
import torch

In [7]:
torch.randint(10,50,(7,))

tensor([44, 26, 49, 15, 41, 40, 23])

In [8]:
torch.tensor([[1,2,3],[4,5,6],[7,8,9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [9]:
torch.zeros(4,5)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [10]:
torch.ones(8,9)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
torch.empty(2,2)

tensor([[ 5.2898e+14,  4.5654e-41],
        [-3.4749e+37,  3.0688e-41]])

In [13]:
torch.arange(6)

tensor([0, 1, 2, 3, 4, 5])

In [17]:
torch.linspace(start=4,end=8,steps=9)

tensor([4.0000, 4.5000, 5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000])

In [19]:
torch.eye(5,4)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.],
        [0., 0., 0., 0.]])

probabilities

In [25]:
probabilities = torch.tensor([0.1,0.9])
samples = torch.multinomial(probabilities,10,replacement=True)
samples

tensor([1, 1, 0, 1, 1, 1, 1, 1, 0, 1])

In [34]:
rows, columns = 1, 4
random_tensor = torch.rand(rows, columns)

random_tensor_2 = torch.rand(4,19)

random_tensor @ random_tensor_2


tensor([[1.4921, 2.0020, 1.0937, 1.6373, 1.7816, 0.7284, 1.6972, 2.0826, 0.9807,
         1.3090, 1.1398, 2.0833, 1.2283, 2.0478, 1.6490, 1.9995, 1.3938, 1.2217,
         1.5454]])